# Theming
font: JetBrainsMono Nerd Font 12
background: "#282828d0"
color: "#ffffff"
border: "#4986dd"
separator: " ➜ "
border_width: 2
corner_r: 10
padding: 15 # Defaults to corner_r
#rows_per_column: 5 # No limit by default
column_padding: 25 # Defaults to padding

# Anchor and margin
anchor: top # One of center, left, right, top, bottom, bottom-left, top-left, etc.
# Only relevant when anchor is not center
margin_right: 0
margin_bottom: 0
margin_left: 0
margin_top: 0

# namespace to use for the layer shell surface
#namespace: "wlr_which_key"

# Permits key bindings that conflict with compositor key bindings.
# Default is `false`.
inhibit_compositor_keyboard_shortcuts: true

# Try to guess the correct keyboard layout to use. Default is `false`.
auto_kbd_layout: true

menu:
  - key: "a"
    desc: Apps
    submenu:
      - key: "f"
        desc: Firefox
        cmd: firefox
      - key: "t"
        desc: Telegram
        cmd: Telegram
      - key: "k"
        desc: Kitty
        cmd: kitty
      - key: "b"
        desc: thunderbird
        cmd: thunderbird
      - key: "e"
        desc: thunar
        cmd: thunar
      - key: "c"
        desc: bscode
        cmd: code
  - key: "w"
    desc: mango
    submenu:
      - key: "w"
        desc: swap win up
        cmd: mmsg -d exchange_client,up
        keep_open: true
      - key: "s"
        desc: swap win down
        cmd: mmsg -d exchange_client,down
        keep_open: true
      - key: "a"
        desc: swap win left
        cmd: mmsg -d exchange_client,left
        keep_open: true
      - key: "d"
        desc: swap win right
        cmd: mmsg -d exchange_client,right
        keep_open: true
      - key: "i"
        desc: resize win up
        cmd: mmsg -d resizewin,+0,-50
        keep_open: true
      - key: "k"
        desc: resize win down
        cmd: mmsg -d resizewin,+0,+50
        keep_open: true
      - key: "j"
        desc: resize win left
        cmd: mmsg -d resizewin,-50,+0
        keep_open: true
      - key: "l"
        desc: resize win right
        cmd: mmsg -d resizewin,+50,+0
        keep_open: true
      - key: "Up"
        desc: move win up
        cmd: mmsg -d movewin,+0,-50
        keep_open: true
      - key: "Down"
        desc: move win down
        cmd: mmsg -d movewin,+0,+50
        keep_open: true
      - key: "Left"
        desc: move win left
        cmd: mmsg -d movewin,-50,+0
        keep_open: true
      - key: "Right"
        desc: move win right
        cmd: mmsg -d movewin,+50,+0
        keep_open: true
      - key: "g"
        desc: toggle global
        cmd: mmsg -d toggleglobal
        keep_open: true
      - key: "f"
        desc: toggle fullscreen window
        cmd: mmsg -d togglefullscreen
        keep_open: true
      - key: "t"
        desc: toggle floating window
        cmd: mmsg -d togglefloating
        keep_open: true
      - key: "m"
        desc: toggle maximize window
        cmd: mmsg -d togglemaximizescreen
        keep_open: true
      - key: "ü"
        desc: toggle fakefullscreen window
        cmd: mmsg -d togglefakefullscreen
        keep_open: true
      - key: "ö"
        desc: minimize window
        cmd: mmsg -d minimized
        keep_open: true
      - key: "ä"
        desc: restore window
        cmd: mmsg -d restore_minimized
        keep_open: true
      - key: "y"
        desc: toggle overlay
        cmd: mmsg -d toggleoverlay
        keep_open: true
