# Theming
font: JetBrainsMono Nerd Font 12
background: "#282828d0"
color: "#ffffff"
border: "#4986dd"
separator: " âžœ "
border_width: 2
corner_r: 10
padding: 15 # Defaults to corner_r
#rows_per_column: 5 # No limit by default
column_padding: 25 # Defaults to padding

# Anchor and margin
anchor: top # One of center, left, right, top, bottom, bottom-left, top-left, etc.
# Only relevant when anchor is not center
margin_right: 0
margin_bottom: 0
margin_left: 0
margin_top: 0

# namespace to use for the layer shell surface
#namespace: "wlr_which_key"

# Permits key bindings that conflict with compositor key bindings.
# Default is `false`.
inhibit_compositor_keyboard_shortcuts: true

# Try to guess the correct keyboard layout to use. Default is `false`.
auto_kbd_layout: true

menu:
    - key: "f"
      desc: Firefox
      cmd: firefox
    - key: "t"
      desc: Telegram
      cmd: Telegram
    - key: "k"
      desc: Kitty
      cmd: kitty
    - key: "b"
      desc: thunderbird
      cmd: thunderbird
    - key: "e"
      desc: thunar
      cmd: thunar
    - key: "c"
      desc: bscode
      cmd: code